import React from 'react';
import {AbsoluteFill, Audio, Img, Sequence, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';

const C = {bg:'#06100d', panel:'#0b1915', line:'#1d352d', text:'#eff9f4', muted:'#87a198', green:'#37eb8f', blue:'#55c7ff', red:'#ff6174', amber:'#ffc45b'};

const Fade: React.FC<React.PropsWithChildren<{accent?:string}>> = ({children, accent=C.green}) => {
  const frame=useCurrentFrame(); const {fps,durationInFrames}=useVideoConfig();
  const opacity=interpolate(frame,[0,12,durationInFrames-12,durationInFrames],[0,1,1,0]);
  return <AbsoluteFill style={{background:`radial-gradient(circle at 80% 0%, ${accent}20, transparent 38%),${C.bg}`,color:C.text,fontFamily:'Segoe UI,Arial,sans-serif',padding:90,opacity}}>{children}</AbsoluteFill>;
};

const Label:React.FC<React.PropsWithChildren>=({children})=><div style={{fontFamily:'Consolas,monospace',fontWeight:800,fontSize:21,letterSpacing:4,color:C.green}}>{children}</div>;
const Title:React.FC<React.PropsWithChildren<{size?:number}>>=({children,size=82})=><h1 style={{fontSize:size,lineHeight:1.02,letterSpacing:-3,margin:'22px 0 28px',maxWidth:1500}}>{children}</h1>;
const Pill:React.FC<React.PropsWithChildren<{color?:string}>>=({children,color=C.green})=><span style={{border:`2px solid ${color}`,padding:'10px 16px',fontFamily:'Consolas,monospace',fontSize:19,color}}>{children}</span>;

const Hook=()=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const enter=spring({frame:f,fps,config:{damping:16}});return <Fade><div style={{marginTop:110,transform:`translateY(${(1-enter)*45}px)`}}><Label>DATAHUB MCP · GRAPH-AWARE REPAIR</Label><Title size={116}>Catalog drift is a graph problem.<br/><span style={{color:C.blue}}>Meet GraphMedic.</span></Title><p style={{fontSize:32,color:C.muted,maxWidth:1150}}>Evidence-first triage, bounded writeback, and a privacy boundary you can verify.</p></div><div style={{position:'absolute',right:90,bottom:80}}><Pill>SYNTHETIC DATA ONLY</Pill></div></Fade>};

const Problem=()=> <Fade accent={C.red}><Label>THE FAILURE MODE</Label><Title>One blank description can hide a <span style={{color:C.red}}>large blast radius.</span></Title><div style={{display:'flex',alignItems:'center',gap:28,marginTop:45}}>{['Retired source','Orders','Revenue','Executive view'].map((x,i)=><React.Fragment key={x}><div style={{width:300,padding:28,border:`2px solid ${i===1?C.red:C.line}`,background:C.panel}}><div style={{fontSize:25,fontWeight:800}}>{x}</div><div style={{fontSize:18,color:C.muted,marginTop:8}}>{i===0?'deprecated':i===1?'owner + docs missing':i===2?'1 downstream':'decision surface'}</div></div>{i<3&&<div style={{fontSize:48,color:C.muted}}>→</div>}</React.Fragment>)}</div><p style={{fontSize:28,color:C.muted,marginTop:60}}>GraphMedic combines ownership, documentation, lineage, and deprecation evidence into an explainable score.</p></Fade>;

const Dashboard=()=>{const f=useCurrentFrame();const zoom=interpolate(f,[0,420],[1.02,1.16]);return <Fade><Label>LIVE AGAINST DATAHUB OSS</Label><Title size={68}>Search. Inspect. Trace both directions.</Title><div style={{height:690,overflow:'hidden',border:`2px solid ${C.line}`,boxShadow:'0 30px 80px #0008'}}><Img src={staticFile('graphmedic-dashboard.png')} style={{width:'100%',transform:`scale(${zoom})`,transformOrigin:'50% 28%'}}/></div></Fade>};

const Tools=()=> <Fade accent={C.blue}><Label>OFFICIAL DATAHUB MCP SERVER</Label><Title>Every conclusion carries a <span style={{color:C.blue}}>tool trail.</span></Title><div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:18,marginTop:65}}>{[['search','discover opt-in'],['get_entities','verify markers'],['get_lineage','score impact'],['add_tags','bounded repair'],['get_entities','prove write']].map(([a,b],i)=><div key={a} style={{background:C.panel,border:`2px solid ${i===3?C.green:C.line}`,padding:'34px 25px',minHeight:230}}><div style={{fontFamily:'Consolas',fontSize:21,color:C.muted}}>0{i+1}</div><div style={{fontSize:26,fontWeight:900,marginTop:32}}>{a}</div><div style={{fontSize:19,color:C.muted,marginTop:10}}>{b}</div><div style={{fontFamily:'Consolas',fontSize:17,color:C.green,marginTop:38}}>VERIFIED</div></div>)}</div><p style={{fontSize:25,color:C.muted,marginTop:55}}>The UI records tool name, safe argument keys, latency, and result status—never secrets or raw private payloads.</p></Fade>;

const Safety=()=> <Fade><Label>DENY BY DEFAULT</Label><Title>Three independent markers—or the asset is <span style={{color:C.red}}>invisible.</span></Title><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:24,marginTop:50}}>{[['01','graphmedic_demo','URN namespace'],['02','GraphMedicDemo','explicit tag'],['03','SYNTHETIC','classification']].map(([n,v,k])=><div key={n} style={{border:`2px solid ${C.green}`,background:C.panel,padding:38}}><div style={{fontFamily:'Consolas',color:C.muted,fontSize:18}}>{n}</div><div style={{color:C.green,fontSize:31,fontWeight:900,marginTop:30}}>{v}</div><div style={{fontSize:22,color:C.muted,marginTop:8}}>{k}</div></div>)}</div><div style={{display:'flex',gap:18,marginTop:45,flexWrap:'wrap'}}>{['No employer data','No personal records','No arbitrary URNs','No invented owners','No unapproved writes'].map(x=><Pill key={x} color={C.blue}>{x}</Pill>)}</div></Fade>;

const Approval=()=>{const f=useCurrentFrame();const zoom=interpolate(f,[0,420],[1.03,1.13]);return <Fade><Label>HUMAN-CONTROLLED WRITEBACK</Label><Title size={68}>Preview the exact repair. Approve. Verify.</Title><div style={{height:700,overflow:'hidden',border:`2px solid ${C.line}`}}><Img src={staticFile('approval-gate.png')} style={{width:'100%',transform:`scale(${zoom})`,transformOrigin:'50% 45%'}}/></div></Fade>};

const Proof=()=> <Fade accent={C.amber}><Label>RUBRIC-READY EVIDENCE</Label><Title>Built to be useful, testable, and <span style={{color:C.amber}}>honest.</span></Title><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:24,marginTop:42}}>{[['10 / 10','automated tests'],['6','fictional assets'],['5','lineage edges'],['0','privacy scan findings']].map(([v,k])=><div key={k} style={{display:'flex',alignItems:'baseline',gap:24,borderBottom:`2px solid ${C.line}`,padding:'24px 10px'}}><b style={{fontSize:58,color:C.green}}>{v}</b><span style={{fontSize:25,color:C.muted}}>{k}</span></div>)}</div><p style={{fontSize:25,color:C.muted,marginTop:50}}>Apache-2.0 source includes the seed, app, tests, architecture, data policy, and reusable GraphMedic Agent Skill.</p></Fade>;

const Close=()=> <Fade><div style={{marginTop:150}}><Label>GRAPHMEDIC</Label><Title size={112}>See the break.<br/><span style={{color:C.blue}}>Repair with proof.</span></Title><p style={{fontSize:30,color:C.muted}}>DataHub OSS + official MCP server · synthetic by construction · human approved</p></div><div style={{position:'absolute',bottom:85,left:90,right:90,display:'flex',justifyContent:'space-between'}}><Pill>APACHE-2.0</Pill><Pill>SYNTHETIC DATA ONLY</Pill></div></Fade>;

export const GraphMedicDemo:React.FC=()=> <AbsoluteFill style={{background:C.bg}}><Audio src={staticFile('narration.wav')}/><Sequence from={0} durationInFrames={270}><Hook/></Sequence><Sequence from={270} durationInFrames={420}><Problem/></Sequence><Sequence from={690} durationInFrames={480}><Dashboard/></Sequence><Sequence from={1170} durationInFrames={420}><Tools/></Sequence><Sequence from={1590} durationInFrames={420}><Safety/></Sequence><Sequence from={2010} durationInFrames={450}><Approval/></Sequence><Sequence from={2460} durationInFrames={420}><Proof/></Sequence><Sequence from={2880} durationInFrames={720}><Close/></Sequence></AbsoluteFill>;
